name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          purs-tidy: "latest"
          spago: "unstable"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: npm run build

      - name: Build bin
        run: npm run bundle

      - name: Run tests
        run: npm run test:ci

      - name: Verify formatting (Ubuntu only)
        if: runner.os == 'Linux'
        run: npm run check
