name: CI

on:
  push:
    branches: [master]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          psa: "latest"
          spago: "latest"
          purs-tidy: "latest"
      - uses: actions/cache@v2
        # This cache uses the .dhall files to know when it should reinstall
        # and rebuild packages. It caches both the installed packages from
        # the `.spago` directory and compilation artifacts from the `output`
        # directory. When restored the compiler will rebuild any files that
        # have changed.
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: npm install

      - name: Build source (non-Windows)
        if: matrix.os != windows-latest
        run: npm run build

      - name: Build source (Windows only)
        if: matrix.os == windows-latest
        run: npm run build:win

      - name: Build bin (non-Windows)
        if: matrix.os != windows-latest
        run: npm run bundle

      - name: Build bin (Windows only)
        if: matrix.os == windows-latest
        run: npm run bundle

      - name: "Run tests (non-Windows)"
        if: matrix.os != windows-latest
        run: npm run test:ci

      - name: "Run tests (Windows only"
        if: matrix.os == windows-latest
        run: npm run test:ci:win

      - name: Verify formatting
        if: matrix.os != windows-latest
        run: npm run check

      - name: Verify formatting
        if: matrix.os == windows-latest
        run: npm run check:win
