name: CI

on:
  push:
    branches: [master]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          # By default, excluding the below option will checkout the commit
          # that merges the PR triggering this build with the
          # the base branch it targets. Doing that will mess up the logic
          # executed by the `purs-changelog` binary because the PR numbers
          # won't be included in the commits
          # So, we checkout the head commit of the pull request instead.
          # ref: ${{ github.event.pull_request.head.sha }}

          # Fetch all history and tags to ensure we get all commits made
          # in the PR
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: purescript-contrib/setup-purescript@main
      - uses: actions/cache@v2
        # This cache uses the .dhall files to know when it should reinstall
        # and rebuild packages. It caches both the installed packages from
        # the `.spago` directory and compilation artifacts from the `output`
        # directory. When restored the compiler will rebuild any files that
        # have changed.
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: npm run build

      - name: Build bin
        run: npm run bundle

      - name: "Run tests"
        run: npm run test:ci

      - name: Verify formatting (Ubuntu only)
        if: runner.os == 'Linux'
        run: npm run check
