name: CI

on:
  push:
    branches: [master]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all history and tags to ensure we get all commits made
          # in the PR. Otherwise, we only fetch the commit that
          # merges the PR's HEAD to the base branch and prune everything else.
          # This causes the PR numbers to not appear in the commit titles
          # and causes the `update` command's test to fail.
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: purescript-contrib/setup-purescript@main
      - uses: actions/cache@v2
        # This cache uses the .dhall files to know when it should reinstall
        # and rebuild packages. It caches both the installed packages from
        # the `.spago` directory and compilation artifacts from the `output`
        # directory. When restored the compiler will rebuild any files that
        # have changed.
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: npm run build

      - name: Build bin
        run: npm run bundle

      - name: "Run tests"
        run: npm run test:ci

      - name: Verify formatting (Ubuntu only)
        if: runner.os == 'Linux'
        run: npm run check
